[build-system]
requires = ["maturin==1.2.0"]
build-backend = "maturin"

[project]
name = "dagex"
version = "2026.10"
readme = "README_PYPI.md"
requires-python = ">=3.8"

[tool.maturin]
features = ["python"]
